<a href="https://colab.research.google.com/github/DaisyIpatzi/daisyipatzi.github.io/blob/main/assets/ML_Artifacts/Perceptron/ANN_(Excercise_1_and_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Simple Perceptron Example**
*Author: Dr Mike Lakoju, CardiffMet*

We are re-implementing the last code. With Neural networks, most implementation uses large datasets, and it is important to write our code in a more optimized manner. We will be using Numpy Library to achieve this.

# Import Library


In [1]:
import numpy as np

# Lets define the Inputs and weights

With NumPy, we work with arrays. Hence we will need to define our inputs as arrays

In [2]:
inputs = np.array([45, 25])

In [3]:
# Check the type of the inputs

type(inputs)

numpy.ndarray

In [4]:
# check the value at index position 0
inputs[0]

45

# Lets define the weights

In [5]:
# creating the weights as Numpy array

weights = np.array([0.7, 0.1])

In [6]:
# Check the value at index 0

weights[0]

0.7

# Create the Sum Function


The dot function is called the dot product from linear algebra. If you are dealing with a huge dataset, The processing difference between the for loop used in the last notebook and this dot product will significantly be different.

In [7]:
def sum_func(inputs, weights):
    return inputs.dot(weights)


In [8]:
# for weights = [0.7, 0.1]

s_prob1 = sum_func(inputs, weights)
s_prob1

34.0

# Create Step function

In [9]:
def step_function(sum_func):
  if (sum_func >= 1):
    print(f'The Sum Function is greater than or equal to 1')
    return 1
  else:
        print(f'The Sum Function is NOT greater')
        return 0

# Result

In [10]:
step_function(s_prob1 )

The Sum Function is greater than or equal to 1


1

 ## If the is weights = [- 0.7, 0.1]

In [11]:
weights = [-0.7, 0.1]

In [12]:
# for weights = [- 0.7, 0.1]

s_prob2 = sum_func(inputs, weights)

round(s_prob2, 2)  #round to 2 decimal places

-29.0

### Result

In [13]:
step_function(s_prob2 )

The Sum Function is NOT greater


0



---


# **Perceptron and Operator Example**


# Define "Inputs, outputs and weights" as Numpy arrays

In [14]:
# Creating input values as a matrix not as a vector
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

In [15]:
# Chcking the shape of the inputs

inputs.shape

(4, 2)

# Outputs

In [16]:
outputs = np.array([0, 0, 0, 1])

In [17]:
#Checking the shape of the outputs

outputs.shape

(4,)

# Weights

In [18]:
# one weight for x1 and one for x2
weights = np.array([0.0, 0.0])

# Learning Rate

In [19]:
learning_rate = 0.1

# Step function

In [20]:
# This is our Activation function

def step_function(sum):
  if (sum >= 1):
    #print(f'The Sum of Weights is Greater or equal to 1')
    return 1
  else:
        #print(f'The Sum of Weights is NOT > or = to 1')
        return 0

# Process Output

We define a function that allows us to calculate/ process the output. The function accepts an instance of our data, then calculate the sum function using Numpy. Finally, we check the output by passing it through the "Step Function."

In [21]:
def cal_output(instance):
  sum_func = instance.dot(weights)
  return step_function(sum_func)

We pass it as alist in a numpy array ...

In [22]:
cal_output(np.array([[1,1]]))

0

# Train

In [23]:
# Check the number of outputs

len(outputs)

4

In [24]:
# Checking the index of the input at postion 3 ..
# this is the last inpute value
inputs[3]

array([1, 1])

In [25]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

<b>Note that:</b> usually, we will need to define the number of epochs, because we will never really get a value of zero when dealing with real-world data. However, for this small data, we will run the loop till we obtain zero error

In [26]:
def train():
    #
    total_error_value = 1
    # While the total_error_value is not equal to zero. we are asumming that at the start of running our network there will be no zero
    while (total_error_value != 0):
        #making the total_error 0 so we can do other calculations
        total_error_value = 0
        #Looping into each row of the dataset (remember indexing in python starts at zero hence 0-3 which are 4 values)
        for i in range(len(outputs)):
            #Calculating predictions
            prediction = cal_output(inputs[i])
            # Calculating the absolute value of the error
            error = abs(outputs[i] - prediction)
            #Updating the error
            total_error_value  += error

            if error > 0:
                for j in range(len(weights)):
                    #updating the weights for x1 and x2
                    weights[j] = weights[j] + (learning_rate * inputs[i][j] * error)
                    print('Weight updated to: ' + str(weights[j]))
        print('Total error Value: ' + str(total_error_value))

In [27]:
train()

Weight updated to: 0.1
Weight updated to: 0.1
Total error Value: 1
Weight updated to: 0.2
Weight updated to: 0.2
Total error Value: 1
Weight updated to: 0.30000000000000004
Weight updated to: 0.30000000000000004
Total error Value: 1
Weight updated to: 0.4
Weight updated to: 0.4
Total error Value: 1
Weight updated to: 0.5
Weight updated to: 0.5
Total error Value: 1
Total error Value: 0


# Classification

In [29]:
# Now we have the final weights that will be used to classify new instances of the data after training.

weights

array([0.5, 0.5])

In [31]:
cal_output(np.array([0,0]))

0

In [32]:
cal_output(np.array([0,1]))

0

In [33]:
cal_output(np.array([1,0]))

0

In [34]:
cal_output(np.array([1,1]))

1